version: '3.8'
services:
  airflow:
    image: apache/airflow:2.5.0
    environment:
      - SOURCE_DB_URL=${SOURCE_DB_URL}
      - TARGET_DB_URL=${TARGET_DB_URL}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src